version: "3.9"

services:
  db:
    image: postgres:15
    container_name: my_postgres_new
    environment:
      POSTGRES_DB: waitinglist  # New DB for this project
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data_new:/var/lib/postgresql/data  # Use a new volume for the new DB
    ports:
      - "5433:5432"  # Use a different port if needed (e.g., 5433 instead of 5432)

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=waitinglist
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data_new:
